name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: first_test
        type: choice
        options:
          - first_test
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test_welcome_admin
        env:
          bot_token: 6604747356:AAGOg7npHpV0RcP1RMl_58tsorFJCX3vfxQ
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest tests/test_handlers/test_welcome_admin.py::test_welcome_admin